import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock Prisma
vi.mock("@/lib/db", () => ({
  prisma: {
    galleryEntry: {
      findMany: vi.fn(),
    },
  },
}));

// Mock AI client
vi.mock("@/lib/ai/client", () => ({
  clusterGalleryEntries: vi.fn(),
}));

import { POST } from "../route";
import { prisma } from "@/lib/db";
import { clusterGalleryEntries } from "@/lib/ai/client";

const mockedFindMany = vi.mocked(prisma.galleryEntry.findMany);
const mockedCluster = vi.mocked(clusterGalleryEntries);

function createEntry(id: string, category: string, country: string) {
  return {
    id,
    childId: "child-1",
    questId: `quest-${id}`,
    imageUrl: `/api/storage/images/${id}.jpg`,
    talentCategory: category,
    country,
    coordinates: JSON.stringify({ lat: -6.21, lng: 106.85 }),
    questContext: JSON.stringify({
      questTitle: `${category} Quest`,
      dream: `I want to be a ${category} expert`,
      missionSummaries: ["Mission 1", "Mission 2"],
    }),
    clusterGroup: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}

describe("POST /api/gallery/cluster", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns empty clusters when no gallery entries exist", async () => {
    mockedFindMany.mockResolvedValue([]);

    const response = await POST();

    expect(response.status).toBe(200);
    const data = await response.json();
    expect(data.clusters).toEqual([]);
    expect(data.totalEntries).toBe(0);
  });

  it("returns clusters generated by AI for multiple entries", async () => {
    const entries = [
      createEntry("e1", "Engineering", "Indonesia"),
      createEntry("e2", "Engineering", "Japan"),
      createEntry("e3", "Art", "Indonesia"),
    ];
    mockedFindMany.mockResolvedValue(entries as never);

    mockedCluster.mockResolvedValue({
      clusters: [
        {
          id: "cluster-1",
          label: "Robot Builders from Asia",
          description: "2 young talents from Indonesia and Japan are building amazing machines!",
          talentTheme: "Engineering",
          countries: ["Indonesia", "Japan"],
          entryIds: ["e1", "e2"],
        },
        {
          id: "cluster-2",
          label: "Young Artists from Indonesia",
          description: "1 young talent from Indonesia is creating beautiful artwork!",
          talentTheme: "Art",
          countries: ["Indonesia"],
          entryIds: ["e3"],
        },
      ],
    });

    const response = await POST();

    expect(response.status).toBe(200);
    const data = await response.json();
    expect(data.clusters).toHaveLength(2);
    expect(data.totalEntries).toBe(3);

    // First cluster
    expect(data.clusters[0].label).toBe("Robot Builders from Asia");
    expect(data.clusters[0].talentTheme).toBe("Engineering");
    expect(data.clusters[0].countries).toEqual(["Indonesia", "Japan"]);
    expect(data.clusters[0].entries).toHaveLength(2);

    // Second cluster
    expect(data.clusters[1].label).toBe("Young Artists from Indonesia");
    expect(data.clusters[1].entries).toHaveLength(1);
  });

  it("enriches clusters with entry data", async () => {
    const entries = [createEntry("e1", "Engineering", "Indonesia")];
    mockedFindMany.mockResolvedValue(entries as never);

    mockedCluster.mockResolvedValue({
      clusters: [
        {
          id: "cluster-1",
          label: "Robot Builders",
          description: "Amazing builders!",
          talentTheme: "Engineering",
          countries: ["Indonesia"],
          entryIds: ["e1"],
        },
      ],
    });

    const response = await POST();

    const data = await response.json();
    const entry = data.clusters[0].entries[0];
    expect(entry.id).toBe("e1");
    expect(entry.imageUrl).toBe("/api/storage/images/e1.jpg");
    expect(entry.talentCategory).toBe("Engineering");
    expect(entry.country).toBe("Indonesia");
    // childId should NOT be in enriched entries (privacy)
    expect(entry).not.toHaveProperty("childId");
  });

  it("does not require authentication (publicly accessible)", async () => {
    // No session mock — should work without auth
    mockedFindMany.mockResolvedValue([]);

    const response = await POST();
    expect(response.status).toBe(200);
  });

  it("returns 500 when clustering fails", async () => {
    const entries = [createEntry("e1", "Engineering", "Indonesia")];
    mockedFindMany.mockResolvedValue(entries as never);
    mockedCluster.mockRejectedValue(new Error("AI service unavailable"));

    const response = await POST();

    expect(response.status).toBe(500);
    const data = await response.json();
    expect(data.error).toBe("clustering_failed");
  });

  it("passes correct entries to clustering AI", async () => {
    const entries = [
      createEntry("e1", "Engineering", "Indonesia"),
      createEntry("e2", "Art", "Japan"),
    ];
    mockedFindMany.mockResolvedValue(entries as never);

    mockedCluster.mockResolvedValue({
      clusters: [
        {
          id: "cluster-1",
          label: "Test",
          description: "Test",
          talentTheme: "Engineering",
          countries: ["Indonesia"],
          entryIds: ["e1"],
        },
      ],
    });

    await POST();

    expect(mockedCluster).toHaveBeenCalledWith([
      {
        id: "e1",
        talentCategory: "Engineering",
        country: "Indonesia",
        coordinates: { lat: -6.21, lng: 106.85 },
      },
      {
        id: "e2",
        talentCategory: "Art",
        country: "Japan",
        coordinates: { lat: -6.21, lng: 106.85 },
      },
    ]);
  });
});
