/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleAdminRouteRouteImport } from './routes/$locale/admin/route'
import { Route as LocaleRegisterIndexRouteImport } from './routes/$locale/register/index'
import { Route as LocaleQuestIndexRouteImport } from './routes/$locale/quest/index'
import { Route as LocaleParentIndexRouteImport } from './routes/$locale/parent/index'
import { Route as LocaleLoginIndexRouteImport } from './routes/$locale/login/index'
import { Route as LocaleHomeIndexRouteImport } from './routes/$locale/home/index'
import { Route as LocaleGalleryIndexRouteImport } from './routes/$locale/gallery/index'
import { Route as LocaleDiscoverIndexRouteImport } from './routes/$locale/discover/index'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale/admin/index'
import { Route as LocaleGalleryIdRouteImport } from './routes/$locale/gallery/$id'
import { Route as LocaleQuestPreviewIndexRouteImport } from './routes/$locale/quest/preview/index'
import { Route as LocaleQuestNewIndexRouteImport } from './routes/$locale/quest/new/index'
import { Route as LocaleQuestIdIndexRouteImport } from './routes/$locale/quest/$id/index'
import { Route as LocaleParentTipsIndexRouteImport } from './routes/$locale/parent/tips/index'
import { Route as LocaleParentSettingsIndexRouteImport } from './routes/$locale/parent/settings/index'
import { Route as LocaleParentReportsIndexRouteImport } from './routes/$locale/parent/reports/index'
import { Route as LocaleLoginParentIndexRouteImport } from './routes/$locale/login/parent/index'
import { Route as LocaleAdminUsersIndexRouteImport } from './routes/$locale/admin/users/index'
import { Route as LocaleAdminReliabilityIndexRouteImport } from './routes/$locale/admin/reliability/index'
import { Route as LocaleAdminModerationIndexRouteImport } from './routes/$locale/admin/moderation/index'
import { Route as LocaleAdminCodesIndexRouteImport } from './routes/$locale/admin/codes/index'
import { Route as LocaleDiscoverResultsIdRouteImport } from './routes/$locale/discover/results/$id'
import { Route as LocaleQuestIdCompleteIndexRouteImport } from './routes/$locale/quest/$id/complete/index'
import { Route as LocaleParentQuestIdIndexRouteImport } from './routes/$locale/parent/quest/$id/index'
import { Route as LocaleAdminReliabilityRateIndexRouteImport } from './routes/$locale/admin/reliability/rate/index'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAdminRouteRoute = LocaleAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleRegisterIndexRoute = LocaleRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuestIndexRoute = LocaleQuestIndexRouteImport.update({
  id: '/quest/',
  path: '/quest/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleParentIndexRoute = LocaleParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLoginIndexRoute = LocaleLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleHomeIndexRoute = LocaleHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGalleryIndexRoute = LocaleGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDiscoverIndexRoute = LocaleDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAdminRouteRoute,
} as any)
const LocaleGalleryIdRoute = LocaleGalleryIdRouteImport.update({
  id: '/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuestPreviewIndexRoute = LocaleQuestPreviewIndexRouteImport.update({
  id: '/quest/preview/',
  path: '/quest/preview/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuestNewIndexRoute = LocaleQuestNewIndexRouteImport.update({
  id: '/quest/new/',
  path: '/quest/new/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuestIdIndexRoute = LocaleQuestIdIndexRouteImport.update({
  id: '/quest/$id/',
  path: '/quest/$id/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleParentTipsIndexRoute = LocaleParentTipsIndexRouteImport.update({
  id: '/parent/tips/',
  path: '/parent/tips/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleParentSettingsIndexRoute =
  LocaleParentSettingsIndexRouteImport.update({
    id: '/parent/settings/',
    path: '/parent/settings/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleParentReportsIndexRoute =
  LocaleParentReportsIndexRouteImport.update({
    id: '/parent/reports/',
    path: '/parent/reports/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleLoginParentIndexRoute = LocaleLoginParentIndexRouteImport.update({
  id: '/login/parent/',
  path: '/login/parent/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAdminUsersIndexRoute = LocaleAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LocaleAdminRouteRoute,
} as any)
const LocaleAdminReliabilityIndexRoute =
  LocaleAdminReliabilityIndexRouteImport.update({
    id: '/reliability/',
    path: '/reliability/',
    getParentRoute: () => LocaleAdminRouteRoute,
  } as any)
const LocaleAdminModerationIndexRoute =
  LocaleAdminModerationIndexRouteImport.update({
    id: '/moderation/',
    path: '/moderation/',
    getParentRoute: () => LocaleAdminRouteRoute,
  } as any)
const LocaleAdminCodesIndexRoute = LocaleAdminCodesIndexRouteImport.update({
  id: '/codes/',
  path: '/codes/',
  getParentRoute: () => LocaleAdminRouteRoute,
} as any)
const LocaleDiscoverResultsIdRoute = LocaleDiscoverResultsIdRouteImport.update({
  id: '/discover/results/$id',
  path: '/discover/results/$id',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuestIdCompleteIndexRoute =
  LocaleQuestIdCompleteIndexRouteImport.update({
    id: '/quest/$id/complete/',
    path: '/quest/$id/complete/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleParentQuestIdIndexRoute =
  LocaleParentQuestIdIndexRouteImport.update({
    id: '/parent/quest/$id/',
    path: '/parent/quest/$id/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleAdminReliabilityRateIndexRoute =
  LocaleAdminReliabilityRateIndexRouteImport.update({
    id: '/reliability/rate/',
    path: '/reliability/rate/',
    getParentRoute: () => LocaleAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/gallery/$id': typeof LocaleGalleryIdRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/discover/': typeof LocaleDiscoverIndexRoute
  '/$locale/gallery/': typeof LocaleGalleryIndexRoute
  '/$locale/home/': typeof LocaleHomeIndexRoute
  '/$locale/login/': typeof LocaleLoginIndexRoute
  '/$locale/parent/': typeof LocaleParentIndexRoute
  '/$locale/quest/': typeof LocaleQuestIndexRoute
  '/$locale/register/': typeof LocaleRegisterIndexRoute
  '/$locale/discover/results/$id': typeof LocaleDiscoverResultsIdRoute
  '/$locale/admin/codes/': typeof LocaleAdminCodesIndexRoute
  '/$locale/admin/moderation/': typeof LocaleAdminModerationIndexRoute
  '/$locale/admin/reliability/': typeof LocaleAdminReliabilityIndexRoute
  '/$locale/admin/users/': typeof LocaleAdminUsersIndexRoute
  '/$locale/login/parent/': typeof LocaleLoginParentIndexRoute
  '/$locale/parent/reports/': typeof LocaleParentReportsIndexRoute
  '/$locale/parent/settings/': typeof LocaleParentSettingsIndexRoute
  '/$locale/parent/tips/': typeof LocaleParentTipsIndexRoute
  '/$locale/quest/$id/': typeof LocaleQuestIdIndexRoute
  '/$locale/quest/new/': typeof LocaleQuestNewIndexRoute
  '/$locale/quest/preview/': typeof LocaleQuestPreviewIndexRoute
  '/$locale/admin/reliability/rate/': typeof LocaleAdminReliabilityRateIndexRoute
  '/$locale/parent/quest/$id/': typeof LocaleParentQuestIdIndexRoute
  '/$locale/quest/$id/complete/': typeof LocaleQuestIdCompleteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/gallery/$id': typeof LocaleGalleryIdRoute
  '/$locale/admin': typeof LocaleAdminIndexRoute
  '/$locale/discover': typeof LocaleDiscoverIndexRoute
  '/$locale/gallery': typeof LocaleGalleryIndexRoute
  '/$locale/home': typeof LocaleHomeIndexRoute
  '/$locale/login': typeof LocaleLoginIndexRoute
  '/$locale/parent': typeof LocaleParentIndexRoute
  '/$locale/quest': typeof LocaleQuestIndexRoute
  '/$locale/register': typeof LocaleRegisterIndexRoute
  '/$locale/discover/results/$id': typeof LocaleDiscoverResultsIdRoute
  '/$locale/admin/codes': typeof LocaleAdminCodesIndexRoute
  '/$locale/admin/moderation': typeof LocaleAdminModerationIndexRoute
  '/$locale/admin/reliability': typeof LocaleAdminReliabilityIndexRoute
  '/$locale/admin/users': typeof LocaleAdminUsersIndexRoute
  '/$locale/login/parent': typeof LocaleLoginParentIndexRoute
  '/$locale/parent/reports': typeof LocaleParentReportsIndexRoute
  '/$locale/parent/settings': typeof LocaleParentSettingsIndexRoute
  '/$locale/parent/tips': typeof LocaleParentTipsIndexRoute
  '/$locale/quest/$id': typeof LocaleQuestIdIndexRoute
  '/$locale/quest/new': typeof LocaleQuestNewIndexRoute
  '/$locale/quest/preview': typeof LocaleQuestPreviewIndexRoute
  '/$locale/admin/reliability/rate': typeof LocaleAdminReliabilityRateIndexRoute
  '/$locale/parent/quest/$id': typeof LocaleParentQuestIdIndexRoute
  '/$locale/quest/$id/complete': typeof LocaleQuestIdCompleteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/gallery/$id': typeof LocaleGalleryIdRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/discover/': typeof LocaleDiscoverIndexRoute
  '/$locale/gallery/': typeof LocaleGalleryIndexRoute
  '/$locale/home/': typeof LocaleHomeIndexRoute
  '/$locale/login/': typeof LocaleLoginIndexRoute
  '/$locale/parent/': typeof LocaleParentIndexRoute
  '/$locale/quest/': typeof LocaleQuestIndexRoute
  '/$locale/register/': typeof LocaleRegisterIndexRoute
  '/$locale/discover/results/$id': typeof LocaleDiscoverResultsIdRoute
  '/$locale/admin/codes/': typeof LocaleAdminCodesIndexRoute
  '/$locale/admin/moderation/': typeof LocaleAdminModerationIndexRoute
  '/$locale/admin/reliability/': typeof LocaleAdminReliabilityIndexRoute
  '/$locale/admin/users/': typeof LocaleAdminUsersIndexRoute
  '/$locale/login/parent/': typeof LocaleLoginParentIndexRoute
  '/$locale/parent/reports/': typeof LocaleParentReportsIndexRoute
  '/$locale/parent/settings/': typeof LocaleParentSettingsIndexRoute
  '/$locale/parent/tips/': typeof LocaleParentTipsIndexRoute
  '/$locale/quest/$id/': typeof LocaleQuestIdIndexRoute
  '/$locale/quest/new/': typeof LocaleQuestNewIndexRoute
  '/$locale/quest/preview/': typeof LocaleQuestPreviewIndexRoute
  '/$locale/admin/reliability/rate/': typeof LocaleAdminReliabilityRateIndexRoute
  '/$locale/parent/quest/$id/': typeof LocaleParentQuestIdIndexRoute
  '/$locale/quest/$id/complete/': typeof LocaleQuestIdCompleteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/gallery/$id'
    | '/$locale/admin/'
    | '/$locale/discover/'
    | '/$locale/gallery/'
    | '/$locale/home/'
    | '/$locale/login/'
    | '/$locale/parent/'
    | '/$locale/quest/'
    | '/$locale/register/'
    | '/$locale/discover/results/$id'
    | '/$locale/admin/codes/'
    | '/$locale/admin/moderation/'
    | '/$locale/admin/reliability/'
    | '/$locale/admin/users/'
    | '/$locale/login/parent/'
    | '/$locale/parent/reports/'
    | '/$locale/parent/settings/'
    | '/$locale/parent/tips/'
    | '/$locale/quest/$id/'
    | '/$locale/quest/new/'
    | '/$locale/quest/preview/'
    | '/$locale/admin/reliability/rate/'
    | '/$locale/parent/quest/$id/'
    | '/$locale/quest/$id/complete/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale'
    | '/$locale/gallery/$id'
    | '/$locale/admin'
    | '/$locale/discover'
    | '/$locale/gallery'
    | '/$locale/home'
    | '/$locale/login'
    | '/$locale/parent'
    | '/$locale/quest'
    | '/$locale/register'
    | '/$locale/discover/results/$id'
    | '/$locale/admin/codes'
    | '/$locale/admin/moderation'
    | '/$locale/admin/reliability'
    | '/$locale/admin/users'
    | '/$locale/login/parent'
    | '/$locale/parent/reports'
    | '/$locale/parent/settings'
    | '/$locale/parent/tips'
    | '/$locale/quest/$id'
    | '/$locale/quest/new'
    | '/$locale/quest/preview'
    | '/$locale/admin/reliability/rate'
    | '/$locale/parent/quest/$id'
    | '/$locale/quest/$id/complete'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/contact'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/gallery/$id'
    | '/$locale/admin/'
    | '/$locale/discover/'
    | '/$locale/gallery/'
    | '/$locale/home/'
    | '/$locale/login/'
    | '/$locale/parent/'
    | '/$locale/quest/'
    | '/$locale/register/'
    | '/$locale/discover/results/$id'
    | '/$locale/admin/codes/'
    | '/$locale/admin/moderation/'
    | '/$locale/admin/reliability/'
    | '/$locale/admin/users/'
    | '/$locale/login/parent/'
    | '/$locale/parent/reports/'
    | '/$locale/parent/settings/'
    | '/$locale/parent/tips/'
    | '/$locale/quest/$id/'
    | '/$locale/quest/new/'
    | '/$locale/quest/preview/'
    | '/$locale/admin/reliability/rate/'
    | '/$locale/parent/quest/$id/'
    | '/$locale/quest/$id/complete/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/register/': {
      id: '/$locale/register/'
      path: '/register'
      fullPath: '/$locale/register/'
      preLoaderRoute: typeof LocaleRegisterIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quest/': {
      id: '/$locale/quest/'
      path: '/quest'
      fullPath: '/$locale/quest/'
      preLoaderRoute: typeof LocaleQuestIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/parent/': {
      id: '/$locale/parent/'
      path: '/parent'
      fullPath: '/$locale/parent/'
      preLoaderRoute: typeof LocaleParentIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/login/': {
      id: '/$locale/login/'
      path: '/login'
      fullPath: '/$locale/login/'
      preLoaderRoute: typeof LocaleLoginIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/home/': {
      id: '/$locale/home/'
      path: '/home'
      fullPath: '/$locale/home/'
      preLoaderRoute: typeof LocaleHomeIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/gallery/': {
      id: '/$locale/gallery/'
      path: '/gallery'
      fullPath: '/$locale/gallery/'
      preLoaderRoute: typeof LocaleGalleryIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/discover/': {
      id: '/$locale/discover/'
      path: '/discover'
      fullPath: '/$locale/discover/'
      preLoaderRoute: typeof LocaleDiscoverIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleAdminRouteRoute
    }
    '/$locale/gallery/$id': {
      id: '/$locale/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/$locale/gallery/$id'
      preLoaderRoute: typeof LocaleGalleryIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quest/preview/': {
      id: '/$locale/quest/preview/'
      path: '/quest/preview'
      fullPath: '/$locale/quest/preview/'
      preLoaderRoute: typeof LocaleQuestPreviewIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quest/new/': {
      id: '/$locale/quest/new/'
      path: '/quest/new'
      fullPath: '/$locale/quest/new/'
      preLoaderRoute: typeof LocaleQuestNewIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quest/$id/': {
      id: '/$locale/quest/$id/'
      path: '/quest/$id'
      fullPath: '/$locale/quest/$id/'
      preLoaderRoute: typeof LocaleQuestIdIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/parent/tips/': {
      id: '/$locale/parent/tips/'
      path: '/parent/tips'
      fullPath: '/$locale/parent/tips/'
      preLoaderRoute: typeof LocaleParentTipsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/parent/settings/': {
      id: '/$locale/parent/settings/'
      path: '/parent/settings'
      fullPath: '/$locale/parent/settings/'
      preLoaderRoute: typeof LocaleParentSettingsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/parent/reports/': {
      id: '/$locale/parent/reports/'
      path: '/parent/reports'
      fullPath: '/$locale/parent/reports/'
      preLoaderRoute: typeof LocaleParentReportsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/login/parent/': {
      id: '/$locale/login/parent/'
      path: '/login/parent'
      fullPath: '/$locale/login/parent/'
      preLoaderRoute: typeof LocaleLoginParentIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/admin/users/': {
      id: '/$locale/admin/users/'
      path: '/users'
      fullPath: '/$locale/admin/users/'
      preLoaderRoute: typeof LocaleAdminUsersIndexRouteImport
      parentRoute: typeof LocaleAdminRouteRoute
    }
    '/$locale/admin/reliability/': {
      id: '/$locale/admin/reliability/'
      path: '/reliability'
      fullPath: '/$locale/admin/reliability/'
      preLoaderRoute: typeof LocaleAdminReliabilityIndexRouteImport
      parentRoute: typeof LocaleAdminRouteRoute
    }
    '/$locale/admin/moderation/': {
      id: '/$locale/admin/moderation/'
      path: '/moderation'
      fullPath: '/$locale/admin/moderation/'
      preLoaderRoute: typeof LocaleAdminModerationIndexRouteImport
      parentRoute: typeof LocaleAdminRouteRoute
    }
    '/$locale/admin/codes/': {
      id: '/$locale/admin/codes/'
      path: '/codes'
      fullPath: '/$locale/admin/codes/'
      preLoaderRoute: typeof LocaleAdminCodesIndexRouteImport
      parentRoute: typeof LocaleAdminRouteRoute
    }
    '/$locale/discover/results/$id': {
      id: '/$locale/discover/results/$id'
      path: '/discover/results/$id'
      fullPath: '/$locale/discover/results/$id'
      preLoaderRoute: typeof LocaleDiscoverResultsIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quest/$id/complete/': {
      id: '/$locale/quest/$id/complete/'
      path: '/quest/$id/complete'
      fullPath: '/$locale/quest/$id/complete/'
      preLoaderRoute: typeof LocaleQuestIdCompleteIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/parent/quest/$id/': {
      id: '/$locale/parent/quest/$id/'
      path: '/parent/quest/$id'
      fullPath: '/$locale/parent/quest/$id/'
      preLoaderRoute: typeof LocaleParentQuestIdIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/admin/reliability/rate/': {
      id: '/$locale/admin/reliability/rate/'
      path: '/reliability/rate'
      fullPath: '/$locale/admin/reliability/rate/'
      preLoaderRoute: typeof LocaleAdminReliabilityRateIndexRouteImport
      parentRoute: typeof LocaleAdminRouteRoute
    }
  }
}

interface LocaleAdminRouteRouteChildren {
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
  LocaleAdminCodesIndexRoute: typeof LocaleAdminCodesIndexRoute
  LocaleAdminModerationIndexRoute: typeof LocaleAdminModerationIndexRoute
  LocaleAdminReliabilityIndexRoute: typeof LocaleAdminReliabilityIndexRoute
  LocaleAdminUsersIndexRoute: typeof LocaleAdminUsersIndexRoute
  LocaleAdminReliabilityRateIndexRoute: typeof LocaleAdminReliabilityRateIndexRoute
}

const LocaleAdminRouteRouteChildren: LocaleAdminRouteRouteChildren = {
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
  LocaleAdminCodesIndexRoute: LocaleAdminCodesIndexRoute,
  LocaleAdminModerationIndexRoute: LocaleAdminModerationIndexRoute,
  LocaleAdminReliabilityIndexRoute: LocaleAdminReliabilityIndexRoute,
  LocaleAdminUsersIndexRoute: LocaleAdminUsersIndexRoute,
  LocaleAdminReliabilityRateIndexRoute: LocaleAdminReliabilityRateIndexRoute,
}

const LocaleAdminRouteRouteWithChildren =
  LocaleAdminRouteRoute._addFileChildren(LocaleAdminRouteRouteChildren)

interface LocaleRouteRouteChildren {
  LocaleAdminRouteRoute: typeof LocaleAdminRouteRouteWithChildren
  LocaleContactRoute: typeof LocaleContactRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleGalleryIdRoute: typeof LocaleGalleryIdRoute
  LocaleDiscoverIndexRoute: typeof LocaleDiscoverIndexRoute
  LocaleGalleryIndexRoute: typeof LocaleGalleryIndexRoute
  LocaleHomeIndexRoute: typeof LocaleHomeIndexRoute
  LocaleLoginIndexRoute: typeof LocaleLoginIndexRoute
  LocaleParentIndexRoute: typeof LocaleParentIndexRoute
  LocaleQuestIndexRoute: typeof LocaleQuestIndexRoute
  LocaleRegisterIndexRoute: typeof LocaleRegisterIndexRoute
  LocaleDiscoverResultsIdRoute: typeof LocaleDiscoverResultsIdRoute
  LocaleLoginParentIndexRoute: typeof LocaleLoginParentIndexRoute
  LocaleParentReportsIndexRoute: typeof LocaleParentReportsIndexRoute
  LocaleParentSettingsIndexRoute: typeof LocaleParentSettingsIndexRoute
  LocaleParentTipsIndexRoute: typeof LocaleParentTipsIndexRoute
  LocaleQuestIdIndexRoute: typeof LocaleQuestIdIndexRoute
  LocaleQuestNewIndexRoute: typeof LocaleQuestNewIndexRoute
  LocaleQuestPreviewIndexRoute: typeof LocaleQuestPreviewIndexRoute
  LocaleParentQuestIdIndexRoute: typeof LocaleParentQuestIdIndexRoute
  LocaleQuestIdCompleteIndexRoute: typeof LocaleQuestIdCompleteIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAdminRouteRoute: LocaleAdminRouteRouteWithChildren,
  LocaleContactRoute: LocaleContactRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleGalleryIdRoute: LocaleGalleryIdRoute,
  LocaleDiscoverIndexRoute: LocaleDiscoverIndexRoute,
  LocaleGalleryIndexRoute: LocaleGalleryIndexRoute,
  LocaleHomeIndexRoute: LocaleHomeIndexRoute,
  LocaleLoginIndexRoute: LocaleLoginIndexRoute,
  LocaleParentIndexRoute: LocaleParentIndexRoute,
  LocaleQuestIndexRoute: LocaleQuestIndexRoute,
  LocaleRegisterIndexRoute: LocaleRegisterIndexRoute,
  LocaleDiscoverResultsIdRoute: LocaleDiscoverResultsIdRoute,
  LocaleLoginParentIndexRoute: LocaleLoginParentIndexRoute,
  LocaleParentReportsIndexRoute: LocaleParentReportsIndexRoute,
  LocaleParentSettingsIndexRoute: LocaleParentSettingsIndexRoute,
  LocaleParentTipsIndexRoute: LocaleParentTipsIndexRoute,
  LocaleQuestIdIndexRoute: LocaleQuestIdIndexRoute,
  LocaleQuestNewIndexRoute: LocaleQuestNewIndexRoute,
  LocaleQuestPreviewIndexRoute: LocaleQuestPreviewIndexRoute,
  LocaleParentQuestIdIndexRoute: LocaleParentQuestIdIndexRoute,
  LocaleQuestIdCompleteIndexRoute: LocaleQuestIdCompleteIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
